sudo: true
dist: trusty
language: python
python:
  - "3.5"
jobs:
  include:
    # trigger systemtests build
    script: |
      curl -LO --retry 3 https://raw.githubusercontent.com/shkodm/systemtests/master/trigger_systemtests.py
      python trigger_systemtests.py --adapter calculix

